### ISSUE TITLE
Allow to add processors via configuration

### ISSUE THREAD

**Issue by KingCrunch** [symfony/monolog-bundle#104]
Monolog and the Monolog-bridge come with some pre-defined processors to use. It would be nice, if one could enable them easily via configuration, like

``` yaml
monolog:
  handlers: ~ # define your handlers here (omitted)
  processors:
    foo:
      type: memory_peak_usage
      real_usage: true
      use_formatting: false
      channels: [bar, baz]
    bar:
      type: psr_log_message
      handlers: [mainfile]
```

**Comment by nicolas-san** [comment]
In the http://symfony.com/fr/doc/current/reference/configuration/monolog.html you have : 
        # Exemples:
        syslog:
            type:                stream
            path:                /var/log/symfony.log
            level:               ERROR
            bubble:              false
            formatter:           my_formatter
            processors:
                - some_callable
With processors, but : 
Unrecognized options "processors" under "monolog.handlers.syslog"
when I try to use it, and after a quick search no trace of "processors" in 
https://github.com/symfony/MonologBundle/blob/master/DependencyInjection/Configuration.php

**Comment by nicoschoenmaker** [comment]
It took me a while to [find](
http://stackoverflow.com/questions/25305126/monolog-processors-not-working-with-symfony) that the current solution to make monolog PSR-3 compatible was to add:
```
monolog.processor.psr_log_message_processor:
    class: Monolog\Processor\PsrLogMessageProcessor
    tags:
        - { name: monolog.processor }
```
But this feels too complicated to me, so :+1: for this issue (or for making the `PsrLogMessageProcessor` a default processor).
