### ISSUE TITLE
app.DEBUG issue

### ISSUE THREAD

**Issue by evgeny-s** [symfony/monolog-bundle#150]
Hello.
I'm a little confused or issue exists. 
I use Monolog in Symfony2 (2.3.18) project with standard configuration:
config_dev.yml

``` yml
monolog:
    handlers:
        main:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        firephp:
            type:  firephp
            level: info
        chromephp:
            type:  chromephp
            level: info
```

config_prod.yml:

``` yml
monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
```

There is a question: 
Why in my prod log I see lines, started with app.DEBUG.
This log is appearing when guzzle (1.1.4) sending success request (status 200) in prod environment. 
Why "app.DEBUG" errors get to the prod.log when I have "action_level" == "error"?
