### ISSUE TITLE
Monolog log rotation locks command executing

### ISSUE THREAD

**Issue by ddimitrioglo** [symfony/monolog-bundle#189]
I have `monolog` configuration like:

```
monolog:
    handlers:
        main:
            type:  rotating_file
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
```
The issue is that commands which are running a long time get locked when log file changes its name (ex: from `var/logs/prod-2016-11-14.log` to `var/logs/prod-2016-11-15.log`)

Is there a hook how to avoid such behaviour?
