### ISSUE TITLE
Configuration prepend fails with exclusive channels

### ISSUE THREAD

**Issue by neemzy** [symfony/monolog-bundle#205]
Let's picture the following configuration:

```yaml
monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]
```

When you try to add a handler through another bundle's extension class, as follows:

```php
public function prepend(ContainerBuilder $container)
{
    // Add handler configuration to MonologBundle
    $configs = $container->getExtensionConfig('monolog');
    $config = $this->processConfiguration(new Symfony\Bundle\MonologBundle\DependencyInjection\Configuration(), $configs);

    $config['handlers']['some_handler'] = /* ... */;

    $container->prependExtensionConfig('monolog', ['handlers' => $config['handlers']]);
}
```

It fails with the following error:

```
[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
Cannot combine exclusive/inclusive definitions in channels list
```

That's because exclamation points are stripped off when the bundle first parses its own configuration, which it is therefore unable to parse back again when prepended (see https://github.com/symfony/monolog-bundle/blob/master/DependencyInjection/Configuration.php#L614).

I came up with the following quick'n'dirty solution in my extension class, which may help understanding the issue better:

```php
foreach ($config['handlers'] as $name => $handler) {
    if (array_key_exists('channels', $handler) && $handler['channels']['type'] === 'exclusive') {
        $config['handlers'][$name]['channels']['elements'] = array_map(
            function($element) {
                return '!'.ltrim($element, '!');
            },
            $handler['channels']['elements']
        );
    }
}
```

Thanks!
