### ISSUE TITLE
How to override monolog handler classes after PR #170

### ISSUE THREAD

**Issue by mmucklo** [symfony/monolog-bundle#206]
PR #170 removes the .class parameters from the XML file.

The question now is how does one override the default class for something like RotatingFileHandler, for instance to extend it to do something custom, or extra.

The function getHandlerClassByType now is a hard coded list of handler classes:

```php
    private function getHandlerClassByType($handlerType)
    {
        $typeToClassMapping = array(
            'stream' => 'Monolog\Handler\StreamHandler',
            'console' => 'Symfony\Bridge\Monolog\Handler\ConsoleHandler',
// ...
        );

        if (!isset($typeToClassMapping[$handlerType])) {
            throw new \InvalidArgumentException(sprintf('There is no handler class defined for handler "%s".', $handlerType));
        }

        return $typeToClassMapping[$handlerType];
    }
```

For instance, the solution given here no longer works:
https://github.com/symfony/monolog-bundle/issues/67

**Comment by avant1** [comment]
@mmucklo you can use `service` handler type and provide custom service id:

config.yml:
```yml
monolog:
    handlers:
        custom_rotating_file:
            type: service
            id: my_custom_rotating_handler
```

services.yml:
```yml
services:
    my_custom_rotating_handler:
        class: Acme\Logging\MyCustomRotatingFileHandler
```

Not sure if it is documentated, but it is implemented here: [DependencyInjection/MonologExtension.php#L134-L137](https://github.com/symfony/monolog-bundle/blob/ebce76a39a65495a66c34eb1574cc4b9e35a4e64/DependencyInjection/MonologExtension.php#L134-L137)

**Comment by mmucklo** [comment]
Thanks for your response.

1 problem that I see is the case of having multiple MyCustomRotatingFileHandlers.

Now instead of specifying all the arguments for rotating file handlers neatly within the handlers section, I have to create a separate rotating file handler service definition for each handler with the proper filename.

**Comment by avant1** [comment]
Seems like for now there is no workaround for defining all configuration in one place.
Maybe this bundle could support syntax like this:

```yml
monolog:
    handlers:
        custom_rotating_file:
            type: service
            service_definition:
                class: Acme\Logging\MyCustomRotatingFileHandler
                arguments:
                    - "foo.txt"
```

Hovewer I'm not sure if symfony DIC can support this and is it common for symfony bundles to have such configuration.

Anyway personally I think that describing services in `config.yml` is not the right place to do that. Separate file (e.g. `logging.yml`) with all handlers definitions there is more appropriate place.
