### ISSUE TITLE
It is not possible to use ENV variable for log level

### ISSUE THREAD

**Issue by asp24** [symfony/monolog-bundle#220]
Due to https://github.com/symfony/monolog-bundle/blob/master/DependencyInjection/MonologExtension.php#L37

it is not possible to specify log level using '%env(LOG_LEVEL%)' string as value

```yaml
monolog:
    handlers:
        main:
            type:         'fingers_crossed'
            action_level: '%env(LOG_LEVEL)%'
            handler:      'nested'
            buffer_size:  10
        nested:
            type:  'stream'
            path:  '%kernel.logs_dir%/%kernel.environment%.log'
            level: 'debug'
        console:
            type:  'console'
```

```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ContextErrorException: Warning: constant(): Couldn't find constant Monolog\Logger::%env(LOG_LEVEL)% in ./vendor/symfony/monolog-bundle/DependencyInjection/MonologExtension.php:42
```
