### ISSUE TITLE
Loggly not receiving the logs

### ISSUE THREAD

**Issue by Mrkisha** [symfony/monolog-bundle#226]
So I've set it up like this:
``` yml
# config.yml
monolog:
    handlers:
        main:
            type: loggly
            token: my-loggly-token
            level: debug
            tag: symfony-app
```

However I receive no logs in Loggly application.
