### ISSUE TITLE
Autowiring & tagging by _defaults does not work together

### ISSUE THREAD

**Issue by gregoirepaqueron** [symfony/monolog-bundle#228]
It looks like the MonologBundle has a priority too high, and runs too early, applying channel tagging before that the services have been autowired. 

In my case : 

```yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        tags:
            - { name: monolog.logger, channel: technical }

    AppBundle\Manager\:
        resource: '../../../src/AppBundle/Manager'
```

My loggers inside my managers are not handled with `technical` channel.

But if i change the service definitions by : 
```yaml
    AppBundle\Manager\:
        resource: '../../../src/AppBundle/Manager'
        arguments:
            - '@logger'
```
it works.

So it looks like MonologBundle find the tag, but there is no logger inside the service to be overridden. Then, the autowiring will run and will put the default logger inside my services, ignoring the tagging.
