### ISSUE TITLE
how to configure an Elastica client to connect to unverified ssl host through the configuration

### ISSUE THREAD

**Issue by nivpenso** [symfony/monolog-bundle#258]
Hello,

I'm trying to create a new elasticsearch handler through the monolog configuration (.yml). This client needs to connect to Elasticsearch server with unverified SSL certificate.

Unfortunately, I'm not able to figure how can I feed the options parameter of the constructor with data through the monolog configuration structure.

`public function __construct(Client $client, array $options = array(), $level = Logger::DEBUG, $bubble = true)`

Can anyone please help me?

**Comment by lyrixx** [comment]
Hello, 

This is not possible via the configuration, you have to declare the service for the client manually:

```yaml
services:
    monolog.elastica.client:
        class: Elastica\Client
        arguments:
            $options: [host: ...,   # see how to configure elastica

monolog:
    handlers:
        elasticsearch:
            type: elasticsearch
            elasticsearch:
                id: monolog.elastica.client
            index: 'my_index'

```
