### ISSUE TITLE
Prod mode does not logging

### ISSUE THREAD

**Issue by kironet** [symfony/monolog-bundle#265]
Hi,

I have a problem, just finished my app, switched to prod mode, but it's not creating prod.log.
Created it manually, but it's not updating. 

Symfony 4.0.9
.env:

```
APP_ENV=prod
APP_DEBUG=1 #also tried 0
```

prod/monolog.yaml:

```
monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        nested:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        console:
            type:   console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine']
```
