### ISSUE TITLE
Support headers for native_mailer

### ISSUE THREAD

**Issue by anthonybocci** [symfony/monolog-bundle#272]
Q|A
-|-
Bug report? | no
Feature request? | yes
BC Break report? | no
RFC? | no
Symfony version | 4.1
Monolog Bundle version|3.3

I am currently using Monolog to receive mails when I log errors. With the `swift_mailer` handler I don't receive any mails using `sendmail` transport. I am used to use `NativeMailerHandler` with Monolog so I would like to use it as handler. With `native_handler` I receive emails, but they are always in plain text.

The `swift_mailer` handler does support a `content_type` key that allows to get the mail as text/html.

The [NativeMailerHandler][1] class has a `headers` attribute that could contains a `content-type`. For now only `swift_mailer` is able to send email as html, [native\_mailer][2] doesn't use any 'headers' or 'content_type' keys.

The following example would be fully compatible with `swift_mailer`.

```yaml
monolog:
    handlers:
        main:
            type:       native_mailer
            from_email: 'myemail@example.com'
            to_email:   ['user@example.com']
            subject:    'An error occured'
            level:      error
            formatter:  monolog.formatter.html
            content-type: text/html
```

But this one would be more flexible with the usage of headers.

```yaml
monolog:
    handlers:
        main:
            type:       native_mailer
            from_email: 'myemail@example.com'
            to_email:   ['user@example.com']
            subject:    'An error occured'
            level:      error
            formatter:  monolog.formatter.html
            headers:
                content-type: text/html
```

[1]: https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/NativeMailerHandler.php#L41
[2]: https://github.com/symfony/monolog-bundle/blob/master/DependencyInjection/MonologExtension.php#L469
