### ISSUE TITLE
Ignore specific HTTP codes from logs is not working

### ISSUE THREAD

**Issue by TheFox** [symfony/monolog-bundle#286]
I have this in my `prod/monolog.yaml` file:

```yaml
monolog:
    handlers:
        main:
            type: fingers_crossed
            level: debug
            action_level: error
            handler: nested
            excluded_http_codes:
                - code: 403
                  urls: {  }
                - code: 404
                  urls:
                      - ^/favicon
                      - ^/robots
                      - ^/js
...
```

It does not work. I still get errors for this URLs. On dev everything works like it should. But production is different. It's not working on production. What's wrong here?

**Comment by Seldaek** [comment]
I'm not sure where you got the `- code: 403 ... ` notation from but I don't think it works, see https://symfony.com/doc/current/logging/monolog_exclude_http_codes.html for how it should look.

**Comment by TheFox** [comment]
So does this mean, that it has to look exact like this?

So the third element has always to be a 400-hash instead of an int and for 403 and 404 I cannot add custom URLs? I cannot add custom 403 URLs?

**Comment by Seldaek** [comment]
No you can add custom paths but I wouldn't expand more than it's expended
in the docs, adding the code key there turns it into an array where the key
name is 'code’ instead of an array with the code number as key. I hope this
makes sense

**Comment by TheFox** [comment]
So I guess my `code:` and `urls:` structure is wrong. I'll test it.

**Comment by Seldaek** [comment]
I think this should work:

```yaml

            excluded_http_codes:
                - 403
                - 404:
                      - ^/favicon
                      - ^/robots
                      - ^/js
```

**Comment by TheFox** [comment]
@Seldaek I tried it but it's not working.

**Comment by TheFox** [comment]
@Seldaek Is this already fixed?

**Comment by Seldaek** [comment]
There is no issue here.. it's a configuration thing. And you need to make sure you use the latest version, possibly pre-release, I am not sure tbh.

**Comment by Lampelk** [comment]
Are `200` status codes allowed? I have a health check which floods my logs and would like to exclude (or move to a different channel?) but it doesn't exclude these paths `/ping` and `/health` (404 DOES work - i.e. it is excluded as expected):

```
  monolog:
    handlers:
      main:
        type: fingers_crossed
        action_level: info
        handler: nested
        excluded_http_codes: [ 404, { 200: [ '^/ping', '^/health' ] } ]
        buffer_size: 50
        formatter: monolog.formatter.json
        channels: [ "!event", "!doctrine", "!security" ]
      nested:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.log"
```
