### ISSUE TITLE
Custom Filter

### ISSUE THREAD

**Issue by TheFox** [symfony/monolog-bundle#290]
How can I create a custom filter? Since `excluded_http_codes` isn't working (see #286) I maybe can create a custom filter and use that to filter the codes _manually_.

**Comment by lyrixx** [comment]
Hello, 
You have to create a class that implements [ActivationStrategyInterface](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/FingersCrossed/ActivationStrategyInterface.php). and then use it in the configuration:

```yaml
service:
    App\Your\ActivationStrategy

monolog:
    handlers:
        fingers_crossed:
            type: fingers_crossed
            activation_strategy:     App\Your\ActivationStrategy
            ...
```
