### ISSUE TITLE
Inject easily an Exception Handler

### ISSUE THREAD

**Issue by jsamouh** [symfony/monolog-bundle#299]
Hi,

It would be good to have a new property definition in this bundle to define an exception handler when monolog fails for any reason.

Something like:
```
// monolog.yml
monolog:
    handlers: //....
    exception_handler: '@MyHandler'
```

in Monolog, Logger class proposes a method called `setExceptionHandler` to define a handler when there is any exception inside Monolog handler treatment

What do you think ?
Do you want a PR for this ?
