### ISSUE TITLE
strange configuration parsing of monolog, ??? BC-break after release of 3.4.0 ???

### ISSUE THREAD

**Issue by boris-brtan** [symfony/monolog-bundle#309]
symfony: ^3.4
monolog: 3.4.0

in the case i have something like this
```yaml
monolog:
    channels: ["cron", "slow"]
    handlers:
        main:
            type: fingers_crossed
            buffer_size: 1000
            action_level: warning
            handler: nested
            excluded_404s:
                - ^/
        nested:
            type: stream
            path: "/tmp/logpipe"
            level: debug
        cron:
            type: stream
            path: "/tmp/logpipe"
            channels: cron
            level: debug
```
after merge of #271 monolog config is invalid because the parsed configuration is treated as group type instead of fingers_crossed

**Comment by PetrHeinz** [comment]
The problem is that in `app/config/packages/monolog.yml` we have this handler definition:
```yml
monolog:
    channels: ["cron", "slow"]
    handlers:
        main:
            type: fingers_crossed
            buffer_size: 1000
            action_level: warning
            handler: nested
            excluded_404s:
                - ^/
        nested:
            type: stream
    # ...
```
and in `app/config/packages/dev/monolog.yml` we change the default `fingers_crossed` handler to `group` type:
```
monolog:
    handlers:
        main:
            # change "fingers_crossed" handler to "group" that works as a passthrough to "nested"
            type: group
            members: [ nested ]
```
I've failed to empty the `excluded_404s` configuration from inside the `app/config/packages/dev/monolog.yml`, as the array items only get appended (I've tried `excluded_404s: ~` and `excluded_404s: []` to no avail).

**Comment by PetrHeinz** [comment]
I've been missing something. An mergable configuration can be unset using `excluded_404s: false`

**Comment by PetrHeinz** [comment]
The change in #271 might not be a BC break per-se, but it can complicate things for the users as seen above. Personally, I'm in favor of being a bit more restrictive in configuration and rather throw an exception when an invalid state is detected.

**Comment by COil** [comment]
Looks like the same type of error after 3.4 upgrade : 

    Invalid configuration for path "monolog.handlers.slack": You can only use excluded_http_codes/excluded_404s with a FingersCrossedHandler definition                                                                                                                                                       
    In ExprBuilder.php line 189:
    You can only use excluded_http_codes/excluded_404s with a FingersCrossedHandler definition

**Comment by boris-brtan** [comment]
+1

**Comment by Legenyes** [comment]
+1

**Comment by lyrixx** [comment]
I managed to reproduce it. Everything is well explained in this [comment](https://github.com/symfony/monolog-bundle/issues/309#issuecomment-504877427)

And the following fix makes your application working (and more robust) 

> I've been missing something. An mergable configuration can be unset using excluded_404s: false

thanks @PetrHeinz 

---

I don't think we can do anything here. using `->performNoDeepMerging()` will break too many applications. 

So you should unset the configuration that are not compatible with your handler:

```
monolog:
    handlers:
        main:
            # change "fingers_crossed" handler to "group" that works as a passthrough to "nested"
            type: group
            members: [ nested ]
            excluded_404s: false
```

**Comment by TamasSzigeti** [comment]
I have the same issue with `excluded_http_codes` and overriding with false doesn't help, same result as with `~` or `[]`

**Comment by boris-brtan** [comment]
OK, so the result is that it is not a part of the BC-promise or it is importnant BC-break that should be introduced also in minor?

**Comment by lyrixx** [comment]
This is not covered by the BC promise

**Comment by boris-brtan** [comment]
now i see, OK THX.

**Comment by COil** [comment]
I don't get the point, it breaks existing applications but it's not considered as a BC break ? I understand it can be easily fixed, but what the point of using semver in this case.

**Comment by boris-brtan** [comment]
as i understand it and also experienced it is a BC-break if it is said it is. You can check the BC-promise list.

**Comment by lyrixx** [comment]
@COil Your usage of MonologBundle was incorrect, and someone added a check to ensure the configuration was correct. 
We have [documented Our Backward Compatibility Promise](https://symfony.com/doc/current/contributing/code/bc.html). I may be wrong, but PR #271 did not violate this promise, isn't?

**Comment by TamasSzigeti** [comment]
Here's the reproducer
https://github.com/TamasSzigeti/monolog_bundle_reproduce_309/commits/master

TBH it's not a big deal, it's cleaner to define monolog configs separately per env anyway

**Comment by lyrixx** [comment]
@TamasSzigeti Thanks, I will have a look ASAP

**Comment by PetrHeinz** [comment]
@lyrixx Thanks for the explanation of your point of view on BC, I tried to explain it similarly in https://github.com/symfony/monolog-bundle/issues/309#issuecomment-504884645. :+1: 

Almost every change in code can break *some* applications. That's why it's important to have a BC Promise.

**Comment by COil** [comment]
ok, ok. I'll give a try this weekend for one of my project. Thank you.

**Comment by lyrixx** [comment]
@TamasSzigeti 

You application can not boot:
```
In Configuration.php line 402:
                                                                         
  Warning: array_map(): Expected parameter 2 to be an array, bool given  
```

---

**Anyway, let take a step back on this issue.**

What do you (all) have in mind when you configure monolog globally (`config/packages/monolog.yaml`) then per env (`config/packages/dev/monolog.yaml`) ?
What do you think symfony should do // What did you expect ?

For now, symfony process configuration like following:

It loads the global configuration first:

```yaml
monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
```

Then it (try to) merges it with the env configuration:

```yaml
monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
            excluded_http_codes: false
```

So this results in something really strange. Which configuration should win? The last one? Why?
This could be determined by the kernel though:
```php
    protected function configureContainer(ContainerBuilder $container, LoaderInterface $loader): void
    {
        // ...
        // global
        $loader->load($confDir.'/{packages}/*'.self::CONFIG_EXTS, 'glob');
         // per env
        $loader->load($confDir.'/{packages}/'.$this->environment.'/**/*'.self::CONFIG_EXTS, 'glob');
```

But anyway, what should be done? Should we drop all the previous configuration if a new configuration is met with the same name?
