### ISSUE TITLE
InsighOps handler is missing (but is present in monolog)

### ISSUE THREAD

**Issue by tristanbes** [symfony/monolog-bundle#311]
Hello,

InsightOps handler is supported on Monolog since the *[10 Sep 2017](https://github.com/Seldaek/monolog/blob/1.24.0/src/Monolog/Handler/InsightOpsHandler.php)*

Yet, when I try to configure it on Symfony side with `MonologBundle v3.4.0):
`There is no handler class defined for handler "insightops"`

```
monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: insightops
            excluded_http_codes: [404, 405]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        insightops:
            type: insightops
            token: xxxxxx-xxxxxx-xxxxx
            region: eu
            level: info
```

(also the `region` key seems not to be supported inside the Configuration of the array node)
