### ISSUE TITLE
Level is not being read from config for custom handler

### ISSUE THREAD

**Issue by wildcard27** [symfony/monolog-bundle#322]
I have created a custom handler to push logs to AWS Firehose. Here is the constructor:

```
class FirehoseLogHandler extends AbstractProcessingHandler {

public function __construct(
        FirehoseClient $firehoseClient,
        FormatterInterface $formatter,
        $streamName,
        $level = Logger::INFO,
        $bubble = true
    ) {

        $this->firehoseClient = $firehoseClient;
        $this->streamName = $streamName;
        $this->formatter = $formatter;

        parent::__construct($level, $bubble);
    }
```

And here is my `monolog.yaml` config:

```
monolog:
  handlers:
    firehose_handler:
      type: service
      id: kinesis_stream_handler

    main:
      type: stream
      handler: firehose_handler
      level: error
      channels: ["!event"]

services:
  kinesis_stream_handler:
    class: App\Logger\Handler\FirehoseLogHandler
    arguments:
      $firehoseClient: '@aws.firehose'
      $formatter: '@App\Logger\Formatter\FirehoseLogFormatter'
      $streamName: 'firehose-stream-test'
```

The problem that I am having is that the `$level` is always set to `Logger::INFO` (200), or whatever is set in the constructor. It seems to be ignoring what is set in the yaml config
