### ISSUE TITLE
How to configure monolog without write debug level messages?

### ISSUE THREAD

**Issue by nyatMeat** [symfony/monolog-bundle#328]
I was configured monolog on active level `ERROR`, but many of my modules write a lot of debug messages before error occured. Sometimes it not necessary info and i want to exclude messages with level `DEBUG` from logging. How i can do that? I read a lot of articles, but i couldn't found a solution

>     
      main:
            type: fingers_crossed
            action_level: error
            handler: log_file

        log_file:
            type: rotating_file
            max_files: 5
            path: '%kernel.logs_dir%/prod.log'
Maybe i need to use another hadler?

**Comment by undebutant** [comment]
Looking at the [RotatingFileHandler.php](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/RotatingFileHandler.php#L42) of monolog, you should be able to filter out debug logs using the `level` parameter with something like:
```yaml
monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: log_file

        log_file:
            type: rotating_file
            max_files: 5
            path: '%kernel.logs_dir%/prod.log'
            # Accept every log with info+ severity
            level: info
```

**Comment by Tobion** [comment]
You could also use a filter like

```
warning_filter:
            type: filter
            handler: ...
            accepted_levels: [warning, error]
```

**Comment by thomasbethmont** [comment]
I had the same issue and found the reason. As previous answers didn't helped me to so much, I put a comment here :

fingers_cross handler are not a filter but a buffer and action_level is not a filter level but a **trigger**.
In you example : 
``` 
 main:
        type: fingers_crossed
        action_level: error
        handler: log_file

log_file:
        type: rotating_file
        max_files: 5
        path: '%kernel.logs_dir%/prod.log'
```
while logs level are < level error, logs are not skipped but **buffered**. when a log with level `error` occurs, all previous logs in the buffer are send to ` handler: log_file` that is why you still have `debug` logs in your file.

If you just want to log errors in the file, you could just skip the fingers_crossed
 handler and put it like :

```
main:
        type: rotating_file
        max_files: 5
        path: '%kernel.logs_dir%/prod.log'
        level: error
```
