### ISSUE TITLE
SyslogUdpHandler - Allow setting "rfc" parameter

### ISSUE THREAD

**Issue by gwinn** [symfony/monolog-bundle#342]
The SyslogUdpHandler constructor has a last parameter "rfc", default value is ["self::RFC5424"](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/SyslogUdpHandler.php#L47).
However, the current Monolog Bundle implementation dos not allows to set another value like self::RFC3164.

It will be nice if we can do something like that:

```
monolog:
    handlers:
        syslog:
            type: syslogudp
            host: 127.0.0.1
            port: 514
            level: error
            ident: app
            rfc: 0
```
