### ISSUE TITLE
The child node "type" at path "monolog.handlers.redis" must be configured.

### ISSUE THREAD

**Issue by shahariaazam** [symfony/monolog-bundle#345]
Getting error `The child node "type" at path "monolog.handlers.redis" must be configured.`.

As per the sample configuration for `redis` (found from https://github.com/symfony/monolog-bundle/blob/master/DependencyInjection/Configuration.php#L91)

Here is my configuration.

```
 redis:
    redis:
        #id: optional if host is given
        host: 127.0.0.1
        password: null
        port: 6379
        database: 0
        key_name: monolog_redis
```

But it's throwing exception "The child node "type" at path "monolog.handlers.redis" must be configured.".

I think either I am missing something or that sample configuration needs to be updated
