### ISSUE TITLE
Facing an issue with custome handler to e

### ISSUE THREAD

**Issue by ankit-ilogix** [symfony/monolog-bundle#356]
@xabbuh @Tobion 
I'm facing one issue in Symfony 5.1.2. I need to use a monolog custom handler but after updated changes when I running the cache clear command PHP process going too high. Please review the below code and give your help/suggestion for the same.

```
config/packages/prod/monolog.yaml
monolog:
    channels: ['db']
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        db:
            type: service
            id: app.monolog.db_handler
            channels: [db, doctrine]

```

```
config/services.yaml
App\EventListener\DatabaseActivitySubscriber:
  tags:
    - { name: 'doctrine.event_subscriber' }
app.monolog.db_handler:
  class: App\Handler\MonologDBHandler
  arguments: ['@doctrine.orm.entity_manager']
```
