### ISSUE TITLE
max_files configuration for rotating_file handler ignored

### ISSUE THREAD

**Issue by blundercon** [symfony/monolog-bundle#366]
We have noticed an issue with the following configuration:

```
monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            max_files: 10
        console:
            type: console
```
The logs are rotated fine but older files are not cleaned up. In effect, it is like `max_files` is completely ignored.

Symfony Version: 3.4
Monolog Bundle Version: ^3.0.2

Please let me know whether this is expected or an issue.
