### ISSUE TITLE
Monolog with Symfony Mailer fails on multiple mail receiver when pass mails as the environment value

### ISSUE THREAD

**Issue by ahmetcelikezer** [symfony/monolog-bundle#374]
Hi,

I tried the create mail notifications that sending on application fail `50x`, so I want to send this notification to 2 different developers and I defined the environment value in `.env` like this:

```
    EXCEPTION_NOTIFICATION_MAILS=example@mail.com,example2@mail.com
```

and the monolog configuration is like this:

```yaml
symfony_mailer:
    type: symfony_mailer
    from_email: '%env(EXCEPTION_MAIL_SENDER)%'
    to_email: '%env(csv:EXCEPTION_NOTIFICATION_MAILS)%'
    subject: 'An Error Occurred on Project X! %%message%%'
    level: debug
    formatter: monolog.formatter.html
    content_type: text/html
```
then the application fails.

```
Invalid type for path "monolog.handlers.symfony_mailer.to_email.0". Expected one of "bool", "int", "float", "string", but got "array".
```

Same error throws on `JSON` parser... Am I defining values as malformed or is this a bug/unsupported usage?
