### ISSUE TITLE
Channels are ignored for nested handlers

### ISSUE THREAD

**Issue by ostrolucky** [symfony/monolog-bundle#375]
I am trying to come up with sane default way to configure monolog in our applications and came up with these conditions:
1. Application MUST always log application specific >= INFO messages
1. Application MUST log non-application specific messages in case of error ONLY
1. Application MUST log application specific DEBUG messages in case of error ONLY
1. Application MUST NOT log same message twice, eg. app INFO or DEBUG message

I assumed this would work:

```yml
monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: main_grouped
            excluded_http_codes: [404, 405]
            buffer_size:  50 # How many messages should be saved? Prevent memory leaks
            include_stacktraces: true
        main_grouped:
            type: group
            members: [ non_app, app_debug]
        non_app:
            type: stream
            path: "%kernel.logs_dir%/non-app.log"
            channels: ["!app"]
        app_debug:
            type: stream
            path: "%kernel.logs_dir%/app_debug.log"
            channels: ["app"]
            level: debug
        # info and higher levels messages should be always logged for app channels
        app:
            type: stream
            path: "%kernel.logs_dir%/app.log"
            level: info
            channels: ["app"]
```

So here:
- we have `app` handler taking care of 1st condition
- we have `main` and `main_grouped` handlers as a gateway for error condition mentioned in points 2. and 3.
- we have `non_app` handler for getting all messages except `app`, conforming with point 2.
- we have `app_debug` handler for getting all application debug messages, conforming with point 3.

Now, problem is that `non_app` handler doesn't care that I am excluding `app` channel via `channels: ["!app"]`. This results in message in `app` channel going through both `app` and `non_app` handlers in case of error happening.

**Comment by Pictor13** [comment]
Mmmh, wondering why `!app` doesn't work. However did you try to play with the `bubble: false` setting?
I'm not sure every handlers supports that but it might help your case; or maybe specifying some filter.

**Comment by ostrolucky** [comment]
Changing `bubble` doesn't seem to have an effect :/

**Comment by ostrolucky** [comment]
This issue also makes it pretty much impossible to have fingers crossed handler that is not listening to `request` or `console`, as that's the channel which is used for logging errors. As such, something like this  (which is part of bigger config and this part specifically is meant to log only messages from app channel when error happens) doesn't work, because either `monolog.logger.request` or `monolog.logger.console` is used for errors, but both of them have NullHandler injected only.

```yml
monolog:
    handlers:
        main_nonapp:
            type: fingers_crossed
            action_level: error
            handler: app_debug
            channels: ["app_debug"]
        app_debug:
            type: stream
            path: "%kernel.logs_dir%/app_debug.log"
```

**Comment by syntaxseed** [comment]
Can confirm this bug. I can't get the exclusion of "!app" to work in `main_handler`. So app channel logs get logged in 2 places.

```YAML
monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: main_handler #nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            formatter: monolog.formatter.standard
        main_handler:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.errors.log"
            level: notice
            channels: ["!event", "!app"]
            formatter: monolog.formatter.standard
        app:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.app.log"
            level: notice
            channels: ["app"]
            formatter: monolog.formatter.standard
```
