### ISSUE TITLE
Elasticsearch type + Doctrine channel throwing errors

### ISSUE THREAD

**Issue by DavidGarciaCat** [symfony/monolog-bundle#391]
Good day,

For some reason, my Monolog's configuration with Elasticsearch just works for every channel but for Doctrine.

Other channels seem to work without errors.

This `doctrine` channel error was thrown when running Doctrine Migrations, but after disabling it for the migrations I have confirmed it also fails for Insert, Select and Update operations:

```
In ElasticaHandler.php line 120:

  Error sending messages to Elasticsearch


In Bulk.php line 337:

  Error in one or more bulk request actions:

  index: /monolog/_doc/7i8l-HcBRIsMsJkcYKtx caused object mapping for [context]
  tried to parse field [null] as object, but found a concrete value
```

And these are my configuration details:

```yml
# docker-compose.yml

version: '3.1'

services:

  # ...

  elasticsearch:
    container_name: myproject-elasticsearch
    image: elasticsearch:7.10.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node

  # ...
```

```yml
# config/packages/dev/monolog.yaml

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            handler: elasticsearch
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        elasticsearch:
            type: elasticsearch
            elasticsearch:
                host: '%env(ELASTICSEARCH_HOST)%'
                port: '%env(ELASTICSEARCH_PORT)%'
#            channels: ["!doctrine"]
```

I have checked (connecting to Elaticsearch through a GUI) that other logs are stored as expected, including `request`, `security` and `events` channels among others.

Any suggestions to deal with this problem, or is this actually a bug?

Cheers,
