### ISSUE TITLE
Monolog custom logger non existent service

### ISSUE THREAD

**Issue by leandroluccerini** [symfony/monolog-bundle#409]
My `Symfony 5.2.9` app is running on my local `Apache 2.0` server (on my machine) with `php 8.0.3`

My app is using a custom monolog logger (user_activity), defined both in dev and prod environment 

**dev/monolog.yaml**
```yaml
monolog:
  channels: [ 'user_activity' ]
  handlers:
    main:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: debug
      channels: [ "!event", "!user_activity" ]
    console:
      type: console
      process_psr_3_messages: false
      channels: [ "!event", "!doctrine", "!console", "!user_activity" ]
    user_activity:
      type: rotating_file
      path: "%kernel.logs_dir%/user_activity.log"
      level: debug
      channels: user_activity
      max_files: 14 # 2 settimane
```

**prod/monolog.yaml**
```yaml
monolog:
  channels: [ 'user_activity' ]
  handlers:
    main:
      type: fingers_crossed
      action_level: error
      handler: nested
      excluded_http_codes: [ 404, 405 ]
      buffer_size: 50 # How many messages should be saved? Prevent memory leaks
    nested:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: debug
      channels: [ "!user_activity" ]
    console:
      type: console
      process_psr_3_messages: false
      channels: [ "!event", "!doctrine", "!user_activity" ]
    user_activity:
      type: rotating_file
      path: "%kernel.logs_dir%/user_activity.log"
      level: debug
      channels: user_activity
      max_files: 14 # 2 settimane
```

When i run composer on my local machine it's all ok.

I've deployed in AWS with CodePipeline + Beanstalk (this is using Nginx instead of Apache).
The problem is that the deployment fails due to

**eb-engine.log**

```console
Script cache:clear returned with error code 1
!!
!!  In CheckExceptionOnInvalidReferenceBehaviorPass.php line 86:
!!
!!    The service "App\Model\Payment\StripePayment" has a dependency on a non-exi
!!    stent service "monolog.logger.user_activity". Did you mean one of these: "m
!!    onolog.logger.http_client", "monolog.logger.security"?
!!
!!
!!
Script @auto-scripts was called via post-update-cmd
```

But if i run `php bin/console debug:container monolog` the service is there showing in all of his splendor

[![monolog][1]][1]

Do someone knows whta the h*ll is going on?

  [1]: https://i.stack.imgur.com/ZbXoK.png
