### ISSUE TITLE
Fatal error Attempted to load class "MongoClient" from the global namespace

### ISSUE THREAD

**Issue by cimo23** [symfony/monolog-bundle#420]
https://github.com/symfony/monolog-bundle/blob/92bd02cc10c40605ff5b4cea88a2911e421aed6b/DependencyInjection/MonologExtension.php#L282

bug occur when we use the configuration without Id Service
class MongoClient not compatible with new PHP mongo class 'MongoDB\Client'

```
monolog:
    handlers:
        main:
            type: mongo
            mongo:
               host: '127.0.0.1'
               port: 27017
               user: root
               pass: '123456'
               database: logsDb
               collection: logsCollection
```
