### ISSUE TITLE
Env var not usable with elasticsearch user and password

### ISSUE THREAD

**Issue by fmarchalemisys** [symfony/monolog-bundle#426]
This is not working in `monolog.yaml`:

````
monolog:
    handlers:
        elk:
            type: elasticsearch
            formatter: elastica_formatter
            level: INFO
            elasticsearch:
                transport: https
                host: "%env(ELK_HOST)%"
                port: 9243
                user: "%env(ELK_USER)%"
                password: "%env(ELK_PASSWORD)%"
````
The error message is

````
Environment variables "ELK_USER", "ELK_PASSWORD" are never used. Please, check your container's configuration.
````

It works if the user and password are used in plain instead of environment variables.

Dumping the two variables [here](https://github.com/symfony/monolog-bundle/blob/master/DependencyInjection/MonologExtension.php#L310) shows:

````
"env_1b9e6838d53f59cc_ELK_USER_b09ad074b74ae33fba693bb6c6ba7c05"
"env_1b9e6838d53f59cc_ELK_PASSWORD_bbeec1d8a5b7c8ddd4af0a40ca7c4d8b"
````
I believe the Authorization string should be build using:

````
$user = $container->resolveEnvPlaceholders($handler['elasticsearch']['user'], true)
$password = $container->resolveEnvPlaceholders($handler['elasticsearch']['password'], true)
…
'Authorization' => 'Basic ' . base64_encode($user . ':' . $password)
````
Or am I missing something?
