### ISSUE TITLE
Logs logged multiple times (twice) in dev env due to redefining channels in handlers configuration

### ISSUE THREAD

**Issue by axi** [symfony/monolog-bundle#433]
Hi,

I was since a long time having some logs logged twice on dev, I just figured out why but I'm not sure of the right way to fix it.

here is my handlers configuration:
```
# config/packages/monolog.yaml
monolog:
    handlers:
        worker:
            type: rotating_file
            max_files: 7
            level: !php/const Psr\Log\LogLevel::INFO
            path: '%kernel.logs_dir%/%kernel.environment%/worker.log'
            channels: [ worker ]
            bubble: true
```

```
# config/packages/dev/monolog.yaml
monolog:
    handlers:
        worker:
            type: rotating_file
            max_files: 2
            level: !php/const Psr\Log\LogLevel::DEBUG
            path: '%kernel.logs_dir%/%kernel.environment%/worker.log'
            channels: [worker]
            bubble: true
```

The fact that I'm redefining channels (even if identical) make the worker handler being added twice in LoggerChannelPass (pushHandler two times). I think we can fix it by:
- not redefining identical channels...
- using a array_unique Symfony\Bundle\MonologBundle\DependencyInjection\Configuration when validating channels

I'll try submiting a Pull Request but feel free to tell me if you think about an other (better) way to fix it
