### ISSUE TITLE
symfony 5.4 to 6.x  || symfony/monolog-bundle": "^3.7.1" issue with UdpSocket 

### ISSUE THREAD

**Issue by audain-dg** [symfony/monolog-bundle#435]
After upgrading symfony 5.4 to 6.x i always get :

`NOTICE: PHP message: PHP Fatal error:  Uncaught RuntimeException: The UdpSocket to ..XX..  has been closed and can not be written to anymore in /srv/api/vendor/monolog/monolog/src/Monolog/Handler/SyslogUdp/UdpSocket.php:63`

My monolog config

```
        syslogudp:
            type: syslogudp
            host: '%env(resolve:SYS_LOG_UDP_HOST)%'
            port: '%env(resolve:SYS_LOG_UDP_PORT)%'
            persistent: true
            formatter: monolog.formatter.json
            level: info

```
this current config work very well with symfony 5.4 and monolog 3.5
