### ISSUE TITLE
Monolog error after sentry added

### ISSUE THREAD

**Issue by DZymelka** [symfony/monolog-bundle#447]
After adding sentry to symfony project, many deprecated errors appeared.

One of them:
`User Deprecated: The "Monolog\Logger" class is considered final. It may change without further notice as of its next major version. You should not extend it from "Symfony\Bridge\Monolog\Logger".`

I am using:
- Symfony: 6.1.8 
- Monolog-bundle: 3.2
- Sentry: 3:12 

My sentry.yaml:
```
sentry:
    dsn: '%env(SENTRY_DSN)%'
    register_error_listener: false
    options:
        environment: "%kernel.environment%.%env(APP_DOMAIN)%"
        release: '%env(APP_RELEASE)%'

monolog:
    handlers:
        sentry:
            type: sentry
            level: !php/const Monolog\Logger::ERROR
            hub_id: Sentry\State\HubInterface
```
