### ISSUE TITLE
Segmentation fault on cache:clear when configuring symfony_mailer handler type

### ISSUE THREAD

**Issue by DamienDub** [symfony/monolog-bundle#456]
Hello,

I get a segmentation fault on cache:clear when configuring monolog with a symfony_mailer handler type.
I use Symfony v5.4.21 and monolog-bundle v3.8.0

Here's a small docker based reproducer project:
[myapp-backend.zip](https://github.com/symfony/monolog-bundle/files/11093266/myapp-backend.zip)

To see the error, navigate to app folder and:
- docker compose up -d 
- docker exec -i myapp-backend-php-1 composer install

The first command will build & launch the containers. The second one will download the dependencies. At the end of the download, the cache:clear command is executed but fails with a segfault.

Here's the monolog configuration (which I've simplified by using the documentation example):

```
monolog:
  channels:
    - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

  handlers:
    
    main:
      type: fingers_crossed
      # 500 errors are logged at the critical level
      action_level: critical
      # to also log 400 level errors (but not 404's):
      # action_level: error
      # excluded_http_codes: [404]
      handler: deduplicated

    deduplicated:
      type: deduplication
      handler: symfony_mailer

    symfony_mailer:
      type: symfony_mailer
      from_email: 'error@example.com'
      to_email: 'error@example.com'
      # or list of recipients
      # to_email:   ['dev1@example.com', 'dev2@example.com', ...]
      subject: 'An Error Occurred! %%message%%'
      level: debug
      formatter: monolog.formatter.html
      content_type: text/html

#    symfony_mailer:
#      type: stream
#      path: "%kernel.logs_dir%/%kernel.environment%.log"
```

If I replace the "symfony_mailer" type by a "stream" type (see commented block), the segfault disappears.
I tried many types of configurations with the same result.
I also reproduced the error on an AWS serverless deployment.

Any idea of what I've done wrong ?
