### ISSUE TITLE
Misfunction with the default prod settings and when using custom query to login

### ISSUE THREAD

**Issue by omgslinux** [symfony/monolog-bundle#463]
The default prod settings since about symfony 5 in monolog.yaml are these:
```
when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
```
Unlike the dev settings, which work like a charm, but about causing problems, one basically could think that the only possible problem of these settings is "lack of proper log".
However, I've been working in an app for several years, since symfony 3 (where it worked ok), but when trying to upgrade to symfony 5 (and later, 6.x), it had a weird misfunctionality when a user tried to login in the app. The only difference I could find with other apps new or upgraded that work without problem (except the above mention to "lack of proper log") is that this uses a custom query for login, instead of the default method. Only in some specific circumstances in prod the login worked as expected, while in the rest, it didn't like in dev, without any kind of logging that could help to debug the issue.
Since this "lack of proper log" didn't prevent any other apps to work, I didn't think to cause any misfunction in the app itself. Then I decided to have some log in order to debug the problem by cloning the dev settings in the "main" section of monolog settings for prod, and since by doing nothing else I started to have proper log, I didn't do anything else. The misfunction was still happenning. Only when I decided to clean the prod cache (since I think shouldn't be necessary since there were no changes in the code), I found out that the app worked as expected, and the misfunction went away. I've been able to reproduce this behaviour in the three servers where I've tried to test the upgraded app.
At this moment, I don't know why this happens, and this is the reason why I write this issue, in order to prevent others to find the same problem. There might be an issue somewhere else that leads to this, or it's just that "the new default prod settings are buggy and should be changed".

If you want more details, I started a [thread in stackoverflow](https://stackoverflow.com/questions/77033293/misfunction-in-symfony-5-when-using-custom-query-in-prod-environment/77056025#77056025)

Thanks in advance.
